# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  lane :deploy do
    pilot(
      skip_waiting_for_build_processing: true, # Skip waiting so we don't waist precious build time
      changelog: "This build was uploaded using fastlane",
      ipa: "../build/ios/ipa/flutter_github_actions.ipa" # Path to your IPA file
    )
  end

  lane :promote do |options|
    skip = options[:skip] || true
    version = flutter_version()
    deliver(
      submit_for_review: false,
      automatic_release: true,
      force: true,
      skip_screenshots: skip,
      skip_binary_upload: true,
      overwrite_screenshots: true,
      app_version: version["version_name"],
      precheck_include_in_app_purchases: false
    )
  end
end
