# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Deploy a new version to the Google Play"
  lane :deploy do
    version = flutter_version()
    upload_to_play_store(
      track: 'internal',
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      release_status: "draft",
      aab: '../build/app/outputs/bundle/release/app-release.aab',
      version_code: version["version_code"],
      version_name: version["version_name"] + "-internal+" + version["version_code"],
    )
  end

  desc "Promote version"
  lane :promote do |options|
    skip = options[:skip] || true
    version = flutter_version()
    upload_to_play_store(
      track: "internal",
      track_promote_to: "production",
      skip_upload_metadata: false,
      skip_upload_images: skip,
      skip_upload_screenshots: skip,
      track_promote_release_status: "draft",
      version_code: version["version_code"],
      version_name: version["version_name"],
    )
  end
end
