name: Build and Deploy
on:
  workflow_dispatch:

jobs:
  build_android:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-android
      cancel-in-progress: true
    name: Build and Deploy Android
    runs-on: self-hosted
    env:
      STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
      KEY_JKS: ${{ secrets.KEY_JKS }}
      SEC_JSON: ${{ secrets.SEC_JSON }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3.3.0
        with:
          distribution: "zulu"
          java-version: "17"
      - name: Create Key properties file
        run: |
            cat << EOF > "./android/key.properties"
            storePassword=${{ secrets.STORE_PASSWORD }}
            keyPassword=${{ secrets.STORE_PASSWORD }}
            keyAlias=upload
            storeFile=./key.jks
            EOF
      - name: Decode key file
        run: echo "${{ secrets.KEY_JKS }}" | openssl base64 -d -out key.jks
      - name: Decode sec json file
        run: echo "${{ secrets.SEC_JSON }}" | openssl base64 -d -out ./android/sec.json
      - uses: subosito/flutter-action@v2
      - run: flutter packages pub get
      - run: flutter build appbundle --release
      - name: Fastlane Action
        uses: maierj/fastlane-action@v2.3.0
        with:
          lane: deploy
          subdirectory: android

  build_ios:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-ios
      cancel-in-progress: true
    name: Build and Deploy iOS
    runs-on: self-hosted
    env:
      FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}

    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
    - run: flutter packages pub get
    - run: flutter build ipa --release
    - name: Deploy iOS Beta to TestFlight via Fastlane
      uses: maierj/fastlane-action@v2.3.0
      with:
        lane: ${{ needs.setup.outputs.environment }}
        subdirectory: ios
