name: Tag Release
on:
    workflow_dispatch:
        inputs:
          action:
            type: choice
            description: Action type
            default: none
            options:
            - major
            - minor
            - patch
            - none
jobs:
  tag:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    name: Tag
    runs-on: self-hosted
    permissions:
        # Give the default GITHUB_TOKEN write permission to commit and push the
        # added or changed files to the repository.
        contents: write

    steps:
      - uses: actions/checkout@v4
        with:
            ref: ${{ github.head_ref }}
            fetch-depth: 0 # Fetch all history for tags and branches
      - uses: stikkyapp/update-pubspec-version@v2
        id: update-pubspec-version
        with:
            strategy: ${{ github.event.inputs.action }}
            bump-build: true
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Bump version to ${{ steps.update-pubspec-version.outputs.new-version }}"
          commit_user_name: GitHub Actions
      - uses: rickstaa/action-create-tag@v1
        id: tag_create
        with:
            tag: "release/v${{ steps.update-pubspec-version.outputs.new-version }}"
            tag_exists_error: false
            message: "Release ${{ steps.update-pubspec-version.outputs.new-version }}"
